### GET方法
GET http://localhost:3000/maintenanceRequest
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoxMjM0NTYsInVzZXJuYW1lIjoiZGVmYXVsdF91c2VybmFtZSIsIm1ldGFkYXRhIjp7ImRyaXZlcl9pZCI6IiJ9LCJpc19hY3RpdmUiOnRydWUsImlhdCI6MTc0MjgwMzcyNiwiZXhwIjoxNzQyODkwMTI2fQ.C9wRcBKAnIfYwBPESJ1_IV_0jLJbZmxl82uWxI4x4pI

### POST方法
POST http://localhost:3000/maintenanceRequest
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoxMjM0NTYsInVzZXJuYW1lIjoiZGVmYXVsdF91c2VybmFtZSIsIm1ldGFkYXRhIjp7ImRyaXZlcl9pZCI6IiJ9LCJpc19hY3RpdmUiOnRydWUsImlhdCI6MTc0MjgwMzcyNiwiZXhwIjoxNzQyODkwMTI2fQ.C9wRcBKAnIfYwBPESJ1_IV_0jLJbZmxl82uWxI4x4pI

{
  "request_date":"2023-01-01T00:00:00Z",
  "maintenance_type":"facilities",
  "maintenance_id":"1",
  "request_type":"上报检修",
  "request_description":"监控坏了"
}

### PUT方法
PUT http://localhost:3000/maintenanceRequest/1
Content-Type: application/json
Authorization: Bearer <你的token>

{
  "license_plate": "ABC123",
  "vehicle_type": "电动",
  "capacity": 45,
  "purchase_date": "2023-01-01T00:00:00Z",
  "status": "维修",
  "vehicle_name": "电动公交车",
  "price": 200000,
  "manufacturer": "某厂家",
  "model": "某型号",
  "image_url": "http://example.com/image.jpg"
}

### DELETE方法
DELETE http://localhost:3000/maintenanceRequest/1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoxMjM0NTYsInVzZXJuYW1lIjoiZGVmYXVsdF91c2VybmFtZSIsIm1ldGFkYXRhIjp7ImRyaXZlcl9pZCI6IiJ9LCJpc19hY3RpdmUiOnRydWUsImlhdCI6MTc0MjgwMzcyNiwiZXhwIjoxNzQyODkwMTI2fQ.C9wRcBKAnIfYwBPESJ1_IV_0jLJbZmxl82uWxI4x4pI

### GET方法
GET http://localhost:3000/maintenanceRequest/1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoxMjM0NTYsInVzZXJuYW1lIjoiZGVmYXVsdF91c2VybmFtZSIsIm1ldGFkYXRhIjp7ImRyaXZlcl9pZCI6IiJ9LCJpc19hY3RpdmUiOnRydWUsImlhdCI6MTc0MjgwMzcyNiwiZXhwIjoxNzQyODkwMTI2fQ.C9wRcBKAnIfYwBPESJ1_IV_0jLJbZmxl82uWxI4x4pI