### 修改司机
PATCH http://localhost:3000/driver/6
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoxMjM0NTYsInVzZXJuYW1lIjoiZGVmYXVsdF91c2VybmFtZSIsIm1ldGFkYXRhIjp7ImRyaXZlcl9pZCI6IiJ9LCJpc19hY3RpdmUiOnRydWUsImlhdCI6MTc0MTQ0MDYzNiwiZXhwIjoxNzQxNTI3MDM2fQ.tVO5ovWhe5pSZFOuCojDZFd-w41yn7CJWJM6jcSH0EI

{
    "employee": {
        "name": "刘思",
        "birth_date": "2025-03-06T14:06:54.947Z",
        "gender": "男",
        "address": "广东省",
        "phone_number": "13715788111",
        "id_type": "身份证",
        "id_number": "445121200004041111"
    },
    "driverInfo": {
        "license_type": "公交车驾驶证A1",
        "license_number": "4839438934",
        "license_expiry_date": "2027-03-06T14:06:54.947Z"
    }
}

### delete a driver
DELETE http://localhost:3000/driver/1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoxMjM0NTYsInVzZXJuYW1lIjoiZGVmYXVsdF91c2VybmFtZSIsIm1ldGFkYXRhIjp7ImRyaXZlcl9pZCI6IiJ9LCJpc19hY3RpdmUiOnRydWUsImlhdCI6MTc0MTQyMjA0MCwiZXhwIjoxNzQxNTA4NDQwfQ.V8lybU5Bo8mmIJQHFd3YsV9Hi3zcFJe20mrpX6CFyFM

### create_driver_and_employee
POST http://localhost:3000/driver/create_driver_and_employee
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoxMjM0NTYsInVzZXJuYW1lIjoiZGVmYXVsdF91c2VybmFtZSIsIm1ldGFkYXRhIjp7ImRyaXZlcl9pZCI6IiJ9LCJpc19hY3RpdmUiOnRydWUsImlhdCI6MTc0MTI1Mzc4NSwiZXhwIjoxNzQxMzQwMTg1fQ.uOZW4Z8lmi8lfR8UGRjc0yTcGfFDmBu5JL7GlF9q3ZU

{
  "employee":{
    "name":"zs",
    "birth_date":"2025-03-06T14:06:54.947Z",
    "gender":"男",
    "address":"广东省",
    "phone_number":"13715788111",
    "id_type":"身份证",
    "id_number":"445121200004041111"
  },
  "driverInfo": {
    "license_type":"公交车驾驶证A1",
    "license_number":"4839438934",
    "license_expiry_date":"2027-03-06T14:06:54.947Z"
  }
}

### get all driver
GET http://localhost:3000/driver/getAll?pageSize=12&pageNum=1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoxMjM0NTYsInVzZXJuYW1lIjoiZGVmYXVsdF91c2VybmFtZSIsIm1ldGFkYXRhIjp7ImRyaXZlcl9pZCI6IiJ9LCJpc19hY3RpdmUiOnRydWUsImlhdCI6MTc0MTQyMjA0MCwiZXhwIjoxNzQxNTA4NDQwfQ.V8lybU5Bo8mmIJQHFd3YsV9Hi3zcFJe20mrpX6CFyFM


### getinfo
GET http://localhost:3000/user/getinfo
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoxMjM0NTYsInVzZXJuYW1lIjoiZGVmYXVsdF91c2VybmFtZSIsIm1ldGFkYXRhIjp7ImRyaXZlcl9pZCI6IiJ9LCJpc19hY3RpdmUiOnRydWUsImlhdCI6MTc0MTI1Mzc4NSwiZXhwIjoxNzQxMzQwMTg1fQ.uOZW4Z8lmi8lfR8UGRjc0yTcGfFDmBu5JL7GlF9q3ZU

### try login
POST http://localhost:3000/user/login
Content-Type: application/json

{
  "id":"123456",
  "password":"1234"
}

### Create a new user (POST)
POST http://localhost:3000/user/create_user
Content-Type: application/json

{
  "password_hash": "1234",
  "role_id":2,
  "user_id":123456,
  "is_active": true,
  "metadata": {
    "driver_id": ""
  }
}

### Create a new role
POST http://localhost:3000/user/create_role
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoxMjM0NTYsInVzZXJuYW1lIjoiZGVmYXVsdF91c2VybmFtZSIsIm1ldGFkYXRhIjp7ImRyaXZlcl9pZCI6IiJ9LCJpc19hY3RpdmUiOnRydWUsImlhdCI6MTc0MTI1Mzc4NSwiZXhwIjoxNzQxMzQwMTg1fQ.uOZW4Z8lmi8lfR8UGRjc0yTcGfFDmBu5JL7GlF9q3ZU

{
  "role_name":"普通用户",
  "allowed_routes":[],
  "allowed_actions":[]
}

### Read roles
POST http://localhost:3000/user/read_role


## Get all users (GET)
GET http://localhost:3000/user

### Get user by ID (GET)
GET http://localhost:3000/user/1

### Update user by ID (PUT)
PUT http://localhost:3000/user/1
Content-Type: application/json

{
  "password_hash": "new_hashed_password",
  "role_id": ["role3"],
  "is_active": false,
  "metadata": {
    "driver_id": "driver_002"
  }
}

### Delete user by ID (DELETE)
DELETE http://localhost:3000/user/1