### 所有车站
GET http://localhost:3000/station
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoxMjM0NTYsInVzZXJuYW1lIjoiZGVmYXVsdF91c2VybmFtZSIsIm1ldGFkYXRhIjp7ImRyaXZlcl9pZCI6IiJ9LCJpc19hY3RpdmUiOnRydWUsImlhdCI6MTc0MjAwNDY4NiwiZXhwIjoxNzQyMDkxMDg2fQ.bEmisQfu-_Z-eoVfbmBFrRmAp5n6AFObkgtpHlv0Y3o

### 增加车站
POST http://localhost:3000/station
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoxMjM0NTYsInVzZXJuYW1lIjoiZGVmYXVsdF91c2VybmFtZSIsIm1ldGFkYXRhIjp7ImRyaXZlcl9pZCI6IiJ9LCJpc19hY3RpdmUiOnRydWUsImlhdCI6MTc0NzczNDM1NywiZXhwIjoxNzQ3ODIwNzU3fQ.Da_uv9ae4OcXObMYcbH-Voa2c1hw2tVTdGo5xCTgBuU

{
  "station_name":"鳌围村",
  "location":"110,120"
}
