### 所有
GET http://localhost:3000/facility
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoxMjM0NTYsInVzZXJuYW1lIjoiZGVmYXVsdF91c2VybmFtZSIsIm1ldGFkYXRhIjp7ImRyaXZlcl9pZCI6IiJ9LCJpc19hY3RpdmUiOnRydWUsImlhdCI6MTc0MjgwMzcyNiwiZXhwIjoxNzQyODkwMTI2fQ.C9wRcBKAnIfYwBPESJ1_IV_0jLJbZmxl82uWxI4x4pI

### 创建设施实例
POST http://localhost:3000/facility
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoxMjM0NTYsInVzZXJuYW1lIjoiZGVmYXVsdF91c2VybmFtZSIsIm1ldGFkYXRhIjp7ImRyaXZlcl9pZCI6IiJ9LCJpc19hY3RpdmUiOnRydWUsImlhdCI6MTc0MjU2NTgwNCwiZXhwIjoxNzQyNjUyMjA0fQ.NuFLTdt3SRQFVtDmALQgklYPuXn72rydWGgbHlWbU0Q

{
  "facility_type_id":1,
  "description":"监控1号",
  "location":"station",
  "owner_id":"1"
}
